config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :teachers
  # resources :posts
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users
  root 'manager/students#index'

  namespace :manager do
    resources :classrooms do 

    end

    resources :students do
      member do
        put 'student_restore', to: 'students#student_restore'
        put 'move_higher'
        put 'move_lower'
      end
    end
    get 'student_deleted', to: 'students#student_deleted'
    put 'student_restore', to: 'students#student_restore'
    delete 'permanently_delete/:id', to: 'students#permanently_delete', as: :permanently_delete
  end

  namespace :login do
    resources :logins
  end

  

  get '/admin' => 'manage/admin#index'
end

app/models/student.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: students
#
#  id         :bigint           not null, primary key
#  age        :integer
#  avatar     :string(255)
#  deleted_at :datetime
#  name       :string(255)
#  phone      :string(255)
#  position   :integer
#  song       :string(255)
#  video      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_students_on_deleted_at  (deleted_at)
#
class Student < ApplicationRecord
  # include RankedModel
  # ranks :row_order
  acts_as_paranoid


  mount_uploader :avatar, AvatarUploader
  mount_uploader :video, MediaUploader
  mount_uploader :song, MediaUploader

  has_many :grades, dependent: :destroy
  accepts_nested_attributes_for :grades, update_only: true

  validates :name, presence: true
  validates :age, presence: true

  paginates_per 5
  
  def self.ransackable_attributes(auth_object = nil)
    ["age", "avatar", "created_at", "deleted_at", "id", "name", "phone", "position", "song", "updated_at", "video"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["grades"]
  end
end

app/controllers/manager/students_controller.rb
# frozen_string_literal: true

module Manager
  class StudentsController < ApplicationController
    def index
      # student_sv = StudentService.new
      # @students = student_sv.get_student(params)
      @q = Student.includes(:grades).ransack(params[:q])
      @students = @q.result.order(:position).page params[:page]
    end

    def show
      @student = Student.find_by(id: params[:id])
    end

    def new
      @student = Student.new
      @student.grades.build
    end

    def create
      @student = Student.new
      student_sv = StudentService.new(@student)

      if student_sv.create_student(student_params)
        redirect_to manager_students_url
      else
        render :new, status: :unprocessable_entity
      end

      # @student = Student.new(student_params)
      # if @student.save
      #   redirect_to manager_students_url
      # else
      #   render :new, status: :unprocessable_entity
      # end
    end

    def edit
      @student = Student.find(params[:id])
    end

    def update
      @student = Student.find(params[:id])
      student_sv = StudentService.new(@student)

      if student_sv.update_student(student_params)
        redirect_to manager_students_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      @student = Student.find(params[:id])
      @student.destroy
      redirect_to manager_students_path, status: :see_other
    end

    def student_deleted
      @student_deleteds = Student.only_deleted
    end

    def student_restore
      @student = Student.only_deleted.find(params[:id])
      @restored_student = @student.restore!(recursive: true)
      redirect_to manager_student_deleted_path, notice: "Student was restored"
    end

    def permanently_delete
      @student = Student.only_deleted.find(params[:id])
      @student.really_destroy!
      redirect_to manager_student_deleted_path, notice: "Student has been permanently deleted"
    end

    def move_lower
      @student = Student.find(params[:id])
      student_posti = Student.where("position > ?", @student.position).order("position ASC").first
      if student_posti
        temp_position = student_posti.position
        student_posti.update_column(:position, @student.position)
        @student.update_column(:position, temp_position)
      end
      redirect_to manager_students_path
      # @student.move_lower
      # manager_students_path
    end

    def move_higher
      @student = Student.find(params[:id])
      student_posti = Student.where("position < ?", @student.position).order("position DESC").first
      if student_posti
        temp_position = student_posti.position
        student_posti.update_column(:position, @student.position)
        @student.update_column(:position, temp_position)
      end
      redirect_to manager_students_path
      # @student.move_higher
      # manager_students_path
    end

    private

    def student_params
      params.require(:student).permit(:name, :age, :phone, :avatar, :video, :song,
                                      grades_attributes: %i[id subject semester score])
    end
  end
end

app/helpers/student_helper.rb
# frozen_string_literal: true

module StudentHelper
end

app/views/manager/students/_bootstrap_pagination.html.erb
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <% if @paginator.current_page > 1 %>
      <li class="page-item">
        <%= link_to_unless @paginator.current_page == 1, '<span aria-hidden="true">&laquo;</span>'.html_safe, @paginator.current_page - 1, class: 'page-link' %>
      </li>
    <% end %>
    
    <% @paginator.each_page do |page| %>
      <li class="page-item <%= 'active' if page == @paginator.current_page %>">
        <%= link_to_unless page == @paginator.current_page, page, page, class: 'page-link' %>
      </li>
    <% end %>
    
    <% if @paginator.current_page < @paginator.total_pages %>
      <li class="page-item">
        <%= link_to_unless @paginator.current_page == @paginator.total_pages, '<span aria-hidden="true">&raquo;</span>'.html_safe, @paginator.current_page + 1, class: 'page-link' %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/manager/students/_form.html.erb
<%= form_with(model: [:manager, student]) do |form| %>
  <div class="form-group">
    <%= form.label :name, "Name student :" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Name Student" %>
    <% @student.errors.full_messages_for(:name).each do |e| %>
      <div><%= e %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :age, "Age :" %>
    <%= form.text_field :age, class: "form-control", placeholder: "Age" %>
  </div>
  
  <div class="form-group">
    <%= form.label :phone, "Phone number:" %>
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone" %>
  </div>

  <div class="form-group">
    <%= form.label :avatar, "Link Img" %>
    <%= form.file_field :avatar, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :song, "Link Mp3" %>
    <%= form.file_field :song, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :video, "Link video" %>
    <%= form.file_field :video, class: "form-control" %>
  </div>

  <%= form.add_nested_fields_link :grades %>

  <%= form.nested_fields_for :grades do |grade| %>
    <%= grade.text_field :score, style: "width: 30%", class: "form-control form-control-sm", placeholder: "Score" %>
    <%= grade.select(:subject, Grade.subjects.keys, { style: "width: 30%", class: "form-select form-select-sm" }) %>
    <%= grade.select(:semester, Grade.semesters.keys, { style: "width: 30%", class: "form-select form-select-sm" }) %>
    <%= grade.remove_nested_fields_link 'Remove' %>
  <% end %>
  
  <div>
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>


<%= javascript_include_tag 'nested_form_fields'%>

app/views/manager/students/edit.html.erb
<h1>Update Student</h1>

<%= render "form", student: @student %>

app/views/manager/students/index.html.erb
<h1>Student</h1>
 <%= search_form_for @q, url: manager_students_path, class: 'd-flex' do |f| %>
            <div class="input-group mb-3">
              <%= f.search_field :name_cont, class: 'form-control me-2', placeholder: 'Search' %>
              <div class="input-group-append">
                <%= f.select :grades_subject_eq, options_for_select([['match', 0], ['english', 1], ['history', 2], ["physical", 3]], nil), { prompt: 'Subject...' }, class: 'custom-select' %>
                <label class="input-group-text" for="q_grades_subject_eq">Subject</label>
              </div>
              <%= f.submit 'Search', class: 'btn btn-outline-success', type: 'submit' %>
            </div>
          <% end %>
<div>
    
    <table class="table">
    <thead>
        <tr>
            <th scope="col">STT</th>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">Phone</th>
            <th scope="col">Action</th>
            <th scope="col">Move</th>
        </tr>
    </thead>
    <tbody>
        <% @students.each_with_index do |student, index|%>
        <tr>
        <th scope="row"><%=index+1%></th>
        <td><%= link_to student.name, manager_student_path(student)%></td>
        <td><%=student.age%></td>
        <td><%=student.phone%></td>
        <td>
            <%# <button type="button" class="btn btn-secondary">Custom</button> %>
            <%= link_to "Custom", edit_manager_student_path(student), class: "btn btn-secondary" %>
            <%= link_to "Delete", manager_student_path(student), data: {turbo_method: :delete, turbo_confirm: "Bạn chắc chắn muốn xoá?"}, class: "btn btn-danger" %>
        </td>
        <td>
            <%= link_to "Move up", move_higher_manager_student_path(student), data: {turbo_method: :put}, class: "move_action" %>
            <br>
            <%= link_to "Move down", move_lower_manager_student_path(student), data: {turbo_method: :put}, class: "move_action" %>
        </td>
        </tr>
        <% end %>
    </tbody>
    </table>
    <%= link_to 'Add Student', new_manager_student_path %>
</div>

<%= paginate @students, theme: 'bootstrap-5',pagination_class: "pagination-sm flex-wrap justify-content-center",
                   nav_class: "d-inline-block"%>

app/views/manager/students/new.html.erb
<h1>Add student</h1>

<%= render "form", student: @student %>

app/views/manager/students/show.html.erb
<div>
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">Phone</th>
            <th scope="col">Image</th>
            <th scope="col">Link mp4</th>
            <th scope="col">link mp3</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @student.name%></td>
            <td><%=@student.age%></td>
            <td><%=@student.phone%></td>
            <td>
                <% if @student.avatar_url.present? %>
                <%= image_tag @student.avatar_url, alt: "User Avatar", class: "rounded", style: "width: 4rem; height: 5rem;" %>
                <% else %>
                <!-- Hiển thị một hình ảnh mặc định hoặc thông báo khác tùy thuộc vào trường hợp -->
                <% end %>
            </td>
            <td>
                <% if @student.video_url.present? %>
                <%= video_tag @student.video_url, alt: "Video", class: "rounded", style: "width: 4rem; height: 5rem;" %>
                <% else %>
                <!-- Hiển thị một hình ảnh mặc định hoặc thông báo khác tùy thuộc vào trường hợp -->
                <% end %>
            </td>
            <td>
                <% if @student.song_url.present? %>
                <%= audio_tag @student.song_url, controls: true, alt: "Song", class: "rounded", style: "width: 4rem; height: 5rem;" %>

                <% else %>
                <!-- Hiển thị một hình ảnh mặc định hoặc thông báo khác tùy thuộc vào trường hợp -->
                <% end %>
            </td>
        </tr>
    </tbody>
    </table>

  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Subject</th>
      <th scope="col">Semester</th>
      <th scope="col">Score</th>
    </tr>
  </thead>
  <tbody>
    <% @student.grades.each_with_index do |f, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= f.subject %></td>
      <td><%= f.semester %></td>
      <td><%= f.score %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/manager/students/student_deleted.html.erb
<h1>Student deleted</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">STT</th>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
      <th scope="col">Phone</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @student_deleteds.each_with_index do |student, index| %>
      <tr>
        <td scope="row"><%= index + 1 %></td>
        <td><%= link_to student.name, manager_student_path(student) %></td>
        <td><%= student.age %></td>
        <td><%= student.phone %></td>
        <td>
          <%= link_to "Restore", student_restore_manager_student_path(student),data: {turbo_method: :put, turbo_confirm: "Bạn chắc chắn muốn restore?"}, class: "btn btn-secondary" %>
          <%= link_to "Delete", manager_permanently_delete_path(student),data: {turbo_method: :delete, turbo_confirm: "Bạn chắc chắn muốn xoá?"}, class: "btn btn-secondary" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>