config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :teachers
  # resources :posts
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users
  root 'manager/students#index'

  namespace :manager do
    resources :classrooms do 

    end

    resources :students do
      member do
        put 'student_restore', to: 'students#student_restore'
        put 'move_higher'
        put 'move_lower'
      end
    end
    get 'student_deleted', to: 'students#student_deleted'
    put 'student_restore', to: 'students#student_restore'
    delete 'permanently_delete/:id', to: 'students#permanently_delete', as: :permanently_delete
  end

  namespace :login do
    resources :logins
  end

  

  get '/admin' => 'manage/admin#index'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bt119</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Home', admin_path, class: 'navbar-brand' %>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Add', admin_path, class: 'nav-link active', 'aria-current': 'page' %>
            </li>
          </ul>

          
        </div> 
        
        <% if admin_signed_in? %>
          <p><%= current_admin.email %></p>
          <%= link_to 'Logout Admin', destroy_admin_session_path, method: :delete,data: { turbo_method: "delete" }, class: 'btn btn-outline-success' %>
          
        <% else %>
          <%= link_to 'Login', new_admin_session_path, class: 'btn btn-outline-success' %>
        <% end %>

      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student page</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Home', manager_students_path, class: 'navbar-brand' %>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Add', new_manager_student_path, class: 'nav-link active', 'aria-current': 'page' %>
            </li>
            <li>
              <%= link_to 'Student deleted', manager_student_deleted_path, class: 'nav-link active', 'aria-current': 'page' %>
            </li>
          </ul>

         



        </div> 
        
        <% if user_signed_in? %>
          <p><%= current_user.email %></p>
          <%= link_to 'Logout', destroy_user_session_path, 
            method: :delete,
            class: 'btn btn-outline-success',
            data: { turbo_method: "delete" } %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-success' %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/class.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classroom</title>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>  
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Home', classrooms_path, class: 'navbar-brand' %>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Add', new_classroom_path, class: 'nav-link active', 'aria-current': 'page' %>
            </li>
            <li>
              <%= link_to 'Teacher', teachers_path, class: 'nav-link active', 'aria-current': 'page' %>
            </li>
          </ul>
        </div> 
      </div>
    </nav>
    <%= yield %>
    <%# hidden_field_tag :authenticity_token, form_authenticity_token %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
  </head>
  <body>
    <%= yield %>
  </body>
</html>